<a href="https://colab.research.google.com/github/DeepuKun/Machine-Learning-Practice/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [10]:
df = pd.read_csv('/content/knn_customer_dataset_240_rows.csv')

In [11]:
df.head()

  Customer_ID  Age  Annual_Spending_k      target
0        C025   41               67.9  High Value
1        C007   38               58.0   Low Value
2        C094   58               62.0  High Value
3        C110   54               92.8  High Value
4        C105   56               63.1   Low Value

In [12]:
df.shape

(240, 4)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        240 non-null    object
 1   Age                240 non-null    int64
 2   Annual_Spending_k  240 non-null    float64
 3   target             240 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 7.6+ KB

In [14]:
df.isnull().sum()

Customer_ID          0
Age                  0
Annual_Spending_k    0
target               0
dtype: int64

In [15]:
target_column = "target"

X = df.drop(columns=[target_column])
y = df[target_column]

X.head()

  Customer_ID  Age  Annual_Spending_k
0        C025   41               67.9
1        C007   38               58.0
2        C094   58               62.0
3        C110   54               92.8
4        C105   56               63.1