<a href="https://colab.research.google.com/github/DeepuKun/Machine-Learning-Practice/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Random Forest is a collection of multipl decision trees

Predict laptop buying occurence using Random forest Algorithm

In [29]:
#libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error, confusion_matrix, classification_report, accuracy_score

In [30]:
#load and upload dataset
data = pd.read_csv('/content/laptop_buying_data.csv', na_values=['',' ','NA','null','NULL','none','?'])

In [31]:
data.head()

    Age  Income Student  Credit Score  Location Buys Laptop
0  25.0    High      No         700.0     Urban         Yes
1  30.0    High     Yes         650.0     Urban          No
2  22.0     Low      No         580.0     Rural          No
3  35.0  Medium      No         620.0     Urban         Yes
4  28.0     Low     Yes         690.0  Suburban         Yes

In [32]:
data.isnull().sum()

Age             1
Income          2
Student         1
Credit Score    2
Location        1
Buys Laptop     0
dtype: int64

In [33]:
#data inspection
#rows
data.shape

(52, 6)

In [34]:
#coloums
print(data.columns.tolist())

['Age', 'Income', 'Student', 'Credit Score', 'Location', 'Buys Laptop']

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           51 non-null     float64
 1   Income        50 non-null     object
 2   Student       51 non-null     object
 3   Credit Score  50 non-null     float64
 4   Location      51 non-null     object
 5   Buys Laptop   52 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.6+ KB

In [36]:
data.describe()

             Age  Credit Score
count  51.000000      50.00000
mean   30.901961     675.20000
std     6.714923      65.90779
min    20.000000     560.00000
25%    26.000000     621.25000
50%    30.000000     667.50000
75%    35.000000     720.00000
max    46.000000     810.00000

In [37]:
df = data.dropna()

In [38]:
df.isnull().sum()

Age             0
Income          0
Student         0
Credit Score    0
Location        0
Buys Laptop     0
dtype: int64

In [39]:
df = df.drop_duplicates()

In [40]:
data.describe(include = 'all')

              Age Income Student  Credit Score Location Buys Laptop
count   51.000000     50      51      50.00000       51          52
unique        NaN      3       2           NaN        3           2
top           NaN    Low      No           NaN    Urban         Yes
freq          NaN     17      30           NaN       22          37
mean    30.901961    NaN     NaN     675.20000      NaN         NaN
std      6.714923    NaN     NaN      65.90779      NaN         NaN
min     20.000000    NaN     NaN     560.00000      NaN         NaN
25%     26.000000    NaN     NaN     621.25000      NaN         NaN
50%     30.000000    NaN     NaN     667.50000      NaN         NaN
75%     35.000000    NaN     NaN     720.00000      NaN         NaN
max     46.000000    NaN     NaN     810.00000      NaN         NaN

In [41]:
df.head()

    Age  Income Student  Credit Score  Location Buys Laptop
0  25.0    High      No         700.0     Urban         Yes
1  30.0    High     Yes         650.0     Urban          No
2  22.0     Low      No         580.0     Rural          No
3  35.0  Medium      No         620.0     Urban         Yes
4  28.0     Low     Yes         690.0  Suburban         Yes

In [42]:
X= df.drop("Buys Laptop", axis = 1)
y= df["Buys Laptop"]
numeric_features =['Age','Credit Score']
categorical_features =["Income","Student","Location"]

In [43]:
#Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify = y)

In [46]:
numeric_transformer = Pipeline([
  ("imputer", SimpleImputer(strategy="median"))
])
categorical_transformer = Pipeline([
  ("imputer", SimpleImputer(strategy="most_frequent")),
  ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [47]:
#preprocessing and Random Forest model creating pipeline
preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])
#model pipeline
model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        max_depth=6,
        random_state=42
    ))
])

In [48]:
#train the model
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Age', 'Credit Score']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Income', 'Student',
                                                   'Location'])])),
                ('classifier',
                 RandomForestClassifier(max_depth=6, n_estimators=200,
                                        random_state=42))])

In [49]:
y_pred = model.predict(X_test)
print(y_pred)

['Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No']

In [50]:
#accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0